# Generated by Django 4.0.6 on 2022-07-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_num', models.CharField(max_length=100, verbose_name='PARA_NUM')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='game.paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('', 'NONE'), ('AT', 'ATTACK'), ('DE', 'DEFFENCE')], default='', max_length=2)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='game.content')),
            ],
        ),
    ]
