# Generated by Django 4.0.6 on 2022-07-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_num', models.CharField(max_length=100, verbose_name='PARA_NUM')),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='paragraph',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(choices=[('NO', 'NONE'), ('AT', 'ATTACK'), ('DE', 'DEFFENCE')], default='NO', max_length=2),
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
        migrations.AlterField(
            model_name='choice',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='game.storyboard'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
