# Generated by Django 4.0.6 on 2022-07-24 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_storyboard_remove_content_paragraph_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='content',
            new_name='storyboard',
        ),
        migrations.RemoveField(
            model_name='storyboard',
            name='para_num',
        ),
        migrations.AddField(
            model_name='storyboard',
            name='storyboard_name',
            field=models.CharField(default='', max_length=100, verbose_name='STORYBOARD_NAME'),
        ),
        migrations.CreateModel(
            name='UserStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=5)),
                ('brave', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userStatic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
