# Generated by Django 4.0.6 on 2022-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_storyboard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyboard',
            name='choice_attack',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='storyboard',
            name='choice_defence',
            field=models.CharField(default='', max_length=100),
        ),
    ]
