# Generated by Django 4.0.6 on 2022-07-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_storyboard_choice_attack_storyboard_choice_defence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
