# Generated by Django 4.0.6 on 2022-07-31 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_userstatus_delete_userstatic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyboard',
            name='image',
        ),
    ]
