# Generated by Django 4.0.6 on 2022-08-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_storyboard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='round',
        ),
    ]
