# Generated by Django 4.0.6 on 2022-08-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_userstatus_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyboard',
            name='brave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storyboard',
            name='damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storyboard',
            name='wisdom',
            field=models.IntegerField(default=0),
        ),
    ]
