# Generated by Django 4.0.6 on 2022-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_storyboard_brave_storyboard_damage_storyboard_wisdom'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='save',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
