# Generated by Django 4.0.6 on 2022-08-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_userstatus_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatus',
            old_name='save',
            new_name='savepoint',
        ),
    ]
